// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cucajqnbauuotwhekppy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1Y2FqcW5iYXV1b3R3aGVrcHB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzA4ODQsImV4cCI6MjA2OTU0Njg4NH0.ANXqIAStjcsf2alQbaxJb1H8kes6o1g5849zCd6ETkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});